name: Deploy Public Server with Ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1' # Versi Node.js Anda

      - name: Install dependencies
        run: npm install

      - name: Start Server and Ngrok
        run: |
          echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml
          nohup npm start & # Jalankan server Anda
          nohup ngrok http 3000 & # Jalankan Ngrok
          sleep 5 # Tunggu beberapa detik untuk memastikan Ngrok berjalan
          curl http://127.0.0.1:4040/api/tunnels # Periksa URL publik Ngrok
